# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd750ad43666405357511bd70ad1e979df62b4df2b14ac48c740106e4d2ab83873a754a7474c8b7f9c7219ddbd927b00fd2b474a6fd8d3e523fa404e0b9b0cc2

test:
  secret_key_base: 0ebb9ba1859015b53fe9781dabd789763f079762f15d5ff36646f348013b6c21e62f7325b2422e0f67f953ed7dcd361e9bf34a3764ab623556ded99bd5b0d66b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
